-- Primer problema:

DROP TABLE AGENDA;

CREATE  TABLE AGENDA(
APELLIDO VARCHAR2(30),
NOMBRE VARCHAR(30),
DOMICILIO VARCHAR2(30),
TELEFONO VARCHAR2(11)
);

DESCRIBE AGENDA;

INSERT INTO AGENDA (APELLIDO,NOMBRE,DOMICILIO,TELEFONO ) VALUES ('Acosta', 'Ana', 'Colon 123', '4234567');
INSERT INTO AGENDA VALUES ('Bustamante', 'Betina', 'Avellaneda 135', '4458787');
INSERT INTO AGENDA VALUES ('Lopez', 'Hector', 'Salta 545', '4887788');
INSERT INTO AGENDA VALUES ('Lopez', 'Luis', 'Urquiza 333', '4545454');
INSERT INTO AGENDA VALUES ('Lopez', 'Marisa', 'Urquiza 333', '4545454');

SELECT * FROM AGENDA;

SELECT * FROM AGENDA WHERE NOMBRE='Marisa';

SELECT  NOMBRE,APELLIDO,DOMICILIO FROM AGENDA WHERE APELLIDO ='Lopez';
SELECT NOMBRE,APELLIDO, DOMICILIO FROM AGENDA WHERE APELLIDO = 'lopez'; -- TUPLA EN BLANCO
SELECT NOMBRE, APELLIDO, DOMICILIO FROM AGENDA WHERE APELLIDO ='LOPEZ'; -- TUPLA EN BLANCO
SELECT NOMBRE,APELLIDO, TELEFONO FROM AGENDA WHERE TELEFONO ='4545454';

-- Segundo problema:

DROP  TABLE ARTICULOS;

CREATE TABLE ARTICULOS (
CODIGO NUMBER (5),
NOMBRE VARCHAR2(20),
DESCRIPCION VARCHAR2(30),
PRECIO NUMBER (7,2)
);

DESCRIBE ARTICULOS;

INSERT INTO ARTICULOS (codigo, nombre, descripcion, precio) VALUES (1,'impresora','Epson Stylus C45',400.80);
INSERT INTO ARTICULOS VALUES (2,'impresora','Epson Stylus C85',500);
INSERT INTO ARTICULOS VALUES (3,'monitor','Samsung 14',800);
INSERT INTO ARTICULOS VALUES (5,'teclado','español Biswal',90);

SELECT * FROM ARTICULOS;

SELECT * FROM ARTICULOS WHERE NOMBRE='impresora';

SELECT NOMBRE, CODIGO, DESCRIPCION FROM ARTICULOS WHERE NOMBRE = 'teclado';





